# Generated by Django 5.0.3 on 2024-03-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name_plural': 'Emprestimos'},
        ),
    ]
